c_compiler_version:            # [linux and cuda_compiler_version != "None"]
  - 13                         # [linux and cuda_compiler_version != "None"]
cxx_compiler_version:          # [linux and cuda_compiler_version != "None"]
  - 13                         # [linux and cuda_compiler_version != "None"]
gcc_compiler_version:          # [linux and cuda_compiler_version != "None"]
  - 13                         # [linux and cuda_compiler_version != "None"]
gxx_compiler_version:          # [linux and cuda_compiler_version != "None"]
  - 13                         # [linux and cuda_compiler_version != "None"]
