# conda dependency configuration
# https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors
python:
  - 3.9
  - 3.10
mpi:
  - mpich # [unix]
  #- openmpi # [unix]
petsc:
  - 3.18.5
