c_compiler:    # [win]
  - vs2017     # [win]
  - vs2017     # [win]

cxx_compiler:  # [win]
  - vs2017     # [win]
  - vs2017     # [win]

vc:            # [win]
  - 14.1       # [win]
  - 14.1       # [win]

python:
  - 3.6
  - 3.7
