cgo_compiler:
  - go-cgo
cuda_compiler:
  - nvcc
cuda_compiler_version:
  - None
#  - 9.2
docker_image:
  - condaforge/linux-anvil-comp7
#  - condaforge/linux-anvil-cuda:9.2
zip_keys:
  - - cuda_compiler_version
    - docker_image
boost_cpp:
  - 1.72
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
