channel_sources:
  - conda-forge
  - conda-forge/label/python_rc,conda-forge

python:
  - 3.13.* *_cp313
  - 3.13.* *_cp313t

numpy:
  - 2
  - 2

python_min:
  - 3.13

is_python_min:
  - true
  - false

python_impl:
  - cpython
  - cpython

is_freethreading:
  - false
  - true
