channel_sources:
  - conda-forge/label/python_rc,conda-forge

python:
  - 3.13.* *_cp313t

numpy:
  - 2

python_min:
  - 3.13

is_python_min:
  - true

python_impl:
  - cpython

is_freethreading:
  - true
