# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: prometheus-client
  version: "0.23.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/prometheus_client-${{ version }}.tar.gz
  sha256: 6ae8f9081eaaaf153a2e959d2e6c4f4fb57b12ef76c8c7980202f1e57b48b2ce

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.0
    - pip
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - prometheus_client
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python client for the Prometheus monitoring system.
  license: BSD-2-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/prometheus/client_python

extra:
  recipe-maintainers:
    - rxm7706
