# libadwaita requires NSColor.controlAccentColor introduced in macOS 10.14
c_stdlib_version:
  - 10.14                      # [osx and x86_64]

# itstool and AppStream require libxml2 2.15
libxml2_devel:
  - 2.15
