# libadwaita requires NSColor.controlAccentColor
c_stdlib_version:
  - 11.0                       # [osx]

MACOSX_DEPLOYMENT_TARGET:
  - 11.0                       # [osx]

MACOSX_SDK_VERSION:
  - 11.0                       # [osx]

# itstool and AppStream require libxml2 2.15
libxml2_devel:
  - 2.15
