# libadwaita requires NSColor.controlAccentColor
c_stdlib_version:
  - 10.15                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]

# itstool and AppStream require libxml2 2.15
libxml2_devel:
  - 2.15
