---
# Note on MPI version pinning:
# We pin the MPI versions so the build does not suddently stop working
# Linux:
# - mpich=4.0.3 because of bugs of the 3.* series
# - requires conda-forge
# OSX:
# - mpich=3.4.3 because 4.* is still unstable
# - requires conda-forge
# Windows:
# - msmpi=10.1.1 is the latest as of this commit
mpi:
  - mpich=4.0.3 # [linux]
  - mpich=3.4.3 # [osx]
  - msmpi=10.1.1 # [win]
c_compiler:
  - gxx # [linux]
  - clang # [osx]
  - vs2022 # [win]
c_compiler_version:
  - 12 # [linux]
  - 16 # [osx]
cxx_compiler:
  - gxx # [linux]
  - clangxx # [osx]
  - vs2022 # [win]
cxx_compiler_version:
  - 12 # [linux]
  - 16 # [osx]
# We need MacOS SDK 10.10 to be able to build on macOS Intel
# Download: https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.10.sdk.tar.xz
# Decompress then to /opt: tar -zxvf MacOSX10.10.sdk.tar.xz -C /opt
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.10.sdk # [osx and not arm64]
