jobs:
  # - template: ./.azure-pipelines/azure-pipelines-linux.yml
  - template: ./.azure-pipelines/azure-pipelines-linux-cos7.yml
  
  - template: ./.azure-pipelines/azure-pipelines-osx.yml
  - template: ./.azure-pipelines/azure-pipelines-win.yml
