jobs:
  - template: ./.azure-pipelines/azure-pipelines-linux.yml
  - template: ./.azure-pipelines/azure-pipelines-linux-cos7.yml
  
  - template: ./.azure-pipelines/azure-pipelines-osx.yml

  
  - template: ./.azure-pipelines/azure-pipelines-win.yml
  - job: any_linux_success
    pool:
      vmImage: ubuntu-latest
    dependsOn:
      - linux_64
      - linux_64_cos7
    steps:
      - script: exit 1
        condition: and(failed('linux_64'), failed('linux_64_cos7'))
  
