c_stdlib_version:  # [osx]
  - 11.0                   # [osx]
# Please consult conda-forge/core before doing this
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]