name: build
channels:
- conda-forge
- nodefaults
dependencies:
- python 3.12.*
- conda >=24.9.2
- conda-libmamba-solver >=24.9.0
- conda-build >=25.3.1
- conda-index >=0.3.0
- conda-forge-ci-setup >=4.9.3,<5.0
- conda-forge-pinning *
- frozendict *
- networkx 2.4.*
- rattler-build-conda-compat >=1.2.0,<2.0.0a0

