c_compiler:
  - clang
cxx_compiler:
  - clangxx
c_compiler_version:    # [unix]
- 21                   # [unix]
cxx_compiler_version:  # [unix]
- 21                   # [unix]
c_stdlib_version:  # [osx]
- 13.3  # [osx]
c_stdlib_version:  # [linux]
- 2.34  # [linux]
