c_compiler:
  - clang
cxx_compiler:
  - clangxx
# https://github.com/oven-sh/bun/blob/9484218ba455ba591ebf75ad4fca98b012f3dd13/CONTRIBUTING.md?plain=1#L93
c_compiler_version:    # [unix]
- 21                   # [unix]
cxx_compiler_version:  # [unix]
- 21                   # [unix]
c_stdlib_version:  # [osx]
- 13.3  # [osx]
c_stdlib_version:  # [linux]
- 2.34  # [linux]
