c_compiler:
  - clang
cxx_compiler:
  - clangxx
# https://github.com/oven-sh/bun/blob/9484218ba455ba591ebf75ad4fca98b012f3dd13/CONTRIBUTING.md?plain=1#L93
c_compiler_version:    # [unix]
- 21                   # [unix]
cxx_compiler_version:  # [unix]
- 21                   # [unix]
# https://github.com/oven-sh/bun/blob/b7475d87689307c8f0c4f008e878f4b5fb0cd7da/cmake/tools/SetupMacSDK.cmake#L1
c_stdlib_version:      # [osx]
- 13.0                 # [osx]
# bun uses preadv2 syscall, which got its glibc wrappers in 2.26, see
# https://www.man7.org/linux/man-pages/man2/preadv2.2.html#HISTORY
c_stdlib_version:      # [linux]
- 2.28                 # [linux]
