c_compiler:
  - clang
cxx_compiler:
  - clangxx
c_compiler_version:  # [osx]
- 21  # [osx]
cxx_compiler_version:  # [osx]
- 21  # [osx]
c_compiler_version:  # [linux]
- 19  # [linux]
cxx_compiler_version:  # [linux]
- 19  # [linux]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
- 11.0  # [osx]
c_stdlib_version:  # [osx]
- 11.0  # [osx]
c_stdlib_version:  # [linux]
- 2.34  # [linux]
