c_compiler:
  - clang
cxx_compiler:
  - clangxx
c_compiler_version:
- 21
cxx_compiler_version:
- 21
MACOSX_DEPLOYMENT_TARGET:  # [osx]
- 11.0  # [osx]
c_stdlib_version:  # [osx]
- 11.0  # [osx]
c_stdlib_version:  # [linux]
- 2.39  # [linux]
