MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.1"                 # [osx and x86_64]
c_compiler_version:        # [osx]
  - '12'                   # [osx]
cxx_compiler_version:      # [osx]
  - '12'                   # [osx] 
