# https://www.gnu.org/software/gnulib/manual/html_node/mntent_002eh.html
# Please consult conda-forge/core before doing this
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]

