channel_sources:
  - conda-forge/label/libint_dev,conda-forge

# Note: this file serves no purpose but to suppress:
#   f'Detected different channel_sources in the recipes: {channel_urls} vs. {new_channel_urls}. Consider submitting them in separate PRs'
