# https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - '10.12'                    # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - '10.12'                    # [osx and x86_64]
