c_stdlib_version:
  - '2.28'                   # [linux and x86_64]
  - '11.3'                   # [osx and x86_64]

cross_c_stdlib:
  - sysroot                  # [linux and x86_64]
  - m2w64-sysroot            # [win and x86_64]
  - macosx-sdk               # [osx and x86_64]
cross_c_stdlib_version:
  - '2.28'                   # [linux and x86_64]
  - '12'                     # [win and x86_64]
  - '11.3'                   # [osx and x86_64]

m2w64_c_compiler:            # [win and x86_64]
  - gcc                      # [win and x86_64]
m2w64_c_compiler_version:    # [win and x86_64]
  - '13'                     # [win and x86_64]
m2w64_c_stdlib:              # [win and x86_64]
  - m2w64-sysroot            # [win and x86_64]
m2w64_c_stdlib_version:      # [win and x86_64]
  - '12'                     # [win and x86_64]
m2w64_cxx_compiler:          # [win and x86_64]
  - gxx                      # [win and x86_64]
m2w64_cxx_compiler_version:  # [win and x86_64]
  - '13'                     # [win and x86_64]

docker_image:
  - quay.io/condaforge/linux-anvil-alma-x86_64:8  # [linux and x86_64]
