version:
- "3.8"
- "3.9"
- "3.10"
- "3.11"
- "3.12"
- "3.13"
version_hex:
- "0x03080000"
- "0x03090000"
- "0x030a0000"
- "0x030b0000"
- "0x030c0000"
- "0x030d0000"
zip_keys:
- - version
  - version_hex
