c_stdlib_version:          # [osx]
  - 10.15                  # [osx]
  
m2w64_c_compiler:          # [not unix]
  - gcc                    # [not unix]
m2w64_c_compiler_version:  # [not unix]
  - 15                     # [not unix]
