c_compiler:
  - clang    # [not win]
  - clang-cl   # [win]
c_compiler_version:
  - 20

cxx_compiler:
  - clangxx    # [not win]
  - clang-cl   # [win]
cxx_compiler_version:
  - 20

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]

c_stdlib_version:
  # Linux: minimum version of supported glibc
  - 2.28                       # [linux]

  # macOS: minimum version of the os
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
  
  # Win: means MSVC 14.3+
  - 2022                       # [win]
