CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.15.sdk      # [osx and x86]
  - /opt/MacOSX11.0.sdk       # [osx and arm64]

MACOSX_SDK_VERSION:             # [osx and x86]
  - "10.15"                     # [osx and x86]

c_stdlib_version:               # [osx]
  - 10.15                       # [osx and x86]
  - 11.0                        # [osx and arm64]

target_platform:
  - osx-arm64                 # [osx and arm64]

SDKROOT:                      # [osx and arm64]
  - /opt                      # [osx and arm64]

c_compiler_version:           # [osx]
  - 19                        # [osx]
cxx_compiler_version:         # [osx]
  - 19                        # [osx]

numpy:
  - 1.23
