MACOSX_SDK_VERSION:           # [osx and x86]
  - "10.15"                   # [osx and x86]
MACOSX_DEPLOYMENT_TARGET:     # [osx and x86]
  - "10.15"                   # [osx and x86]

c_stdlib_version:
  - "10.15"                   # [osx and x86]
  - "2.28"                    # [linux]
