m2w64_c_compiler:                 # [win]
  - gcc                           # [win]
m2w64_c_compiler_version:         # [win]
  - 13                            # [win]
m2w64_cxx_compiler:               # [win]
  - gxx                           # [win]
m2w64_cxx_compiler_version:       # [win]
  - 13                            # [win]
m2w64_fortran_compiler:           # [win]
  - gfortran                      # [win]
m2w64_fortran_compiler_version:   # [win]
  - 13                            # [win]
m2w64_c_stdlib:                   # [win]
  - m2w64-sysroot                 # [win]
m2w64_c_stdlib_version:           # [win]
  - 12                            # [win]
m2w64_toolchain:                  # [win]
  - disabled                      # [win]