python:
    - 3.10
    - 3.11
    - 3.12
    - 3.13
    - 3.14
    - 3.9
    - 3.10
    - 3.11
    - 3.12
    - 3.13
    - 3.9
    - 3.10
    - 3.11
    - 3.12
    - 3.13
c_compiler:                # [win]
  - vs2022                 # [win]
cxx_compiler:              # [win]
  - vs2022                 # [win]
vtk_version:
  - 9.5
  - 9.5
  - 9.5
  - 9.5
  - 9.5
  - 9.4
  - 9.4
  - 9.4
  - 9.4
  - 9.4
  - 9.3
  - 9.3
  - 9.3
  - 9.3
  - 9.3
zip_keys:
  - [python, vtk_version]