python_abi_tag:
 - cp27mu  # [linux]
 - cp27m   # [not linux]
 - cp35m
 - cp36m
 - cp37m
 - cp38
 - pypy27_pp73
 - pypy36_pp73

python_requirement:
 - 2.7.*
 - 3.5.*
 - 3.6.*
 - 3.7.*
 - 3.8.*
 - 2.7.* *_73_pypy
 - 3.6.* *_73_pypy

python_version:
 - 2.7
 - 3.5
 - 3.6
 - 3.7
 - 3.8
 - 2.7
 - 3.6

python_impl:
 - cpython
 - cpython
 - cpython
 - cpython
 - cpython
 - pypy
 - pypy

zip_keys:
 -
   - python_abi_tag
   - python_version
   - python_requirement
   - python_impl
