c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2022                     # [win]
c_compiler_version:            # [unix]
  - 14                         # [linux]
  - 19                         # [osx]
  # CUDA 12.6 doesn't support GCC 14
  - 13                         # [linux and cuda_enabled]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.15                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
MACOSX_SDK_VERSION:
  - 10.15                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
gcc_compiler_version:
  - 14                         # [not osx]
  - 15                         # [osx]
libxml2_devel:
  - 2.15
