c_stdlib:
  - macosx_deployment_target   # [osx]
c_compiler:
  - clang                      # [osx]
c_compiler_version:
  - 19                         # [osx]
c_stdlib_version:
  - 10.15                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
gcc_compiler_version:
  - 15                         # [osx]
libxml2_devel:
  - 2.15
