# current rust & its stdlib requires 10.12, see
# https://github.com/rust-lang/rust/pull/104385
# https://github.com/pyca/cryptography/issues/10235
MACOSX_DEPLOYMENT_TARGET:   # [osx and x86_64]
  - "10.12"                 # [osx and x86_64]