c_stdlib_version:          # [osx]
  - "11.0"                # [osx]
MACOSX_SDK_VERSION:          # [osx]
  - "11.0"                # [osx]
c_stdlib:  # [osx]
  - macosx_deployment_target  # [osx]
channel_targets:
  - conda-forge pdal_rc

# values from migrations
gdal:
- '3.9'
libgdal:
- '3.9'
proj:
- '9.4'
tiledb:
- '2.24'
