c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.28                       # [linux]
  - 2.28                       # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
m2w64_c_stdlib:                # [win]
  - m2w64-sysroot              # [win]
m2w64_c_stdlib_version:        # [win]
  - 12                         # [win]
