c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.28                       # [linux]
  - 2.28                       # [linux and not ppc64le and os.environ.get("CF_CUDA_ENABLED", "False") == "True"]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
m2w64_c_stdlib:                # [win]
  - m2w64-sysroot              # [win]
m2w64_c_stdlib_version:        # [win]
  - 12                         # [win]

qemu_system_arch:
  - "aarch64"
  - "ppc64"    # [linux]
  - "riscv64"  # [linux]

zip_keys:
  - - "qemu_user_arch"
    - "qemu_user_cpu"
    - "qemu_user_gcc"
    - "qemu_user_sysroot"
    - "qemu_user_sysroot_version"
qemu_user_arch:
    - "aarch64"
    - "ppc64le"
    - "riscv64"
qemu_user_cpu:
    - "max"
    - "power9"
    - "max"
qemu_user_gcc:
    - "aarch64-conda-linux-gnu-gcc"
    - "powerpc64le-conda-linux-gnu-gcc"
    - "riscv64-conda-linux-gnu-gcc"
qemu_user_sysroot:
    - "aarch64"
    - "powerpc64le"
    - "riscv64"
qemu_user_sysroot_version:
    - "2.28"
    - "2.28"
    - "2.39"

# For reference: System arch list
# - "alpha"
# - "arm"
# - "avr"
# - "cris"
# - "hppa"
# - "i386"
# - "loongarch64"
# - "m68k"
# - "microblaze"
# - "microblazeel"
# - "mips"
# - "mips64"
# - "mips64el"
# - "mipsel"
# - "or1k"
# - "ppc"
# - "riscv32"
# - "rx"
# - "s390x"
# - "sh4"
# - "sh4eb"
# - "sparc"
# - "sparc64"
# - "tricore"
# - "x86_64"
# - "xtensa"
# - "xtensaeb"

# qemu_firmware_list:
#   - firmware/50-edk2-i386-secure.json
#   - firmware/50-edk2-x86_64-secure.json
#   - firmware/60-edk2-aarch64.json
#   - firmware/60-edk2-arm.json
#   - firmware/60-edk2-i386.json
#   - firmware/60-edk2-loongarch64.json
#   - firmware/60-edk2-riscv64.json
#   - firmware/60-edk2-x86_64.json
# 
#   - ast27x0_bootrom.bin
#   - bios-256k.bin
#   - bios.bin
#   - bios-microvm.bin
#   - edk2-aarch64-code.fd
#   - edk2-arm-code.fd
#   - edk2-arm-vars.fd
#   - edk2-i386-code.fd
#   - edk2-i386-secure-code.fd
#   - edk2-i386-vars.fd
#   - edk2-licenses.txt
#   - edk2-loongarch64-code.fd
#   - edk2-loongarch64-vars.fd
#   - edk2-riscv-code.fd
#   - edk2-riscv-vars.fd
#   - edk2-x86_64-code.fd
#   - edk2-x86_64-secure-code.fd
#   - efi-e1000e.rom
#   - efi-e1000.rom
#   - efi-eepro100.rom
#   - efi-ne2k_pci.rom
#   - efi-pcnet.rom
#   - efi-rtl8139.rom
#   - efi-virtio.rom
#   - efi-vmxnet3.rom
#   - hppa-firmware64.img
#   - hppa-firmware.img
#   - kvmvapic.bin
#   - linuxboot.bin
#   - linuxboot_dma.bin
#   - multiboot.bin
#   - multiboot_dma.bin
#   - npcm7xx_bootrom.bin
#   - npcm8xx_bootrom.bin
#   - openbios-ppc
#   - openbios-sparc32
#   - openbios-sparc64
#   - opensbi-riscv32-generic-fw_dynamic.bin
#   - opensbi-riscv64-generic-fw_dynamic.bin
#   - palcode-clipper
#   - pnv-pnor.bin
#   - pvh.bin
#   - pxe-e1000.rom
#   - pxe-eepro100.rom
#   - pxe-ne2k_pci.rom
#   - pxe-pcnet.rom
#   - pxe-rtl8139.rom
#   - pxe-virtio.rom
#   - qboot.rom
#   - QEMU,cgthree.bin
#   - qemu-nsis.bmp
#   - QEMU,tcx.bin
#   - qemu_vga.ndrv
#   - s390-ccw.img
#   - skiboot.lid
#   - slof.bin
#   - u-boot.e500
#   - u-boot-sam460.bin
#   - vgabios-ati.bin
#   - vgabios.bin
#   - vgabios-bochs-display.bin
#   - vgabios-cirrus.bin
#   - vgabios-qxl.bin
#   - vgabios-ramfb.bin
#   - vgabios-stdvga.bin
#   - vgabios-virtio.bin
#   - vgabios-vmware.bin
#   - vof.bin
#   - vof-nvram.bin
