# Require slightly newer SDK to fix build for awl-lc-sys crate
# (SDK 10.14 fixes missing CommonCryptoError.h include in CommonCrypto/CommonCryptoError.h .)
MACOSX_SDK_VERSION:  # [osx and x86_64]
  - "10.14"          # [osx and x86_64]
# Increase minimum deployment target acc. to used SDK version to avoid unintended incompatibilities.
c_stdlib_version:    # [osx and x86_64]
  - "10.14"          # [osx and x86_64]