clangdev:
  - 17.*
  - 13.*
clingdev:
  - 0.17.*
  - 0.13.*
clingdev_tag:
  - ""
  - a292a61b
backend:
  - repl
  - cling
zip_keys:
  -
    - clangdev
    - clingdev
    - clingdev_tag

c_compiler:            # [osx]
  - clang_bootstrap    # [osx]
cxx_compiler:          # [osx]
  - clang_bootstrap    # [osx]
MACOSX_SDK_VERSION:    # [osx and x86_64]
  - 10.12              # [osx and x86_64]
