libstdcxx:  # [linux]
  - 12      # [linux]
  - 13      # [linux]
hdf5:
  - 1.12.2
  - 1.14.3
numpy:
  - 1.26
  - 2.0  #Lowest compatible version
c_stdlib:
  - sysroot                    # [linux]
c_stdlib_version:              # [unix]
  - 2.28                       # [linux and x86_64]
