# See qt-main recipe on qt6 branch
# https://github.com/conda-forge/qt-main-feedstock/blob/qt6/recipe/conda_build_config.yaml
c_stdlib_version:          # [osx]
  - 11.0                   # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]
  
c_stdlib_version:          # [linux]
  - 2.17                   # [linux]
