# This differs from target_platform in that it determines what subdir the compiler
#    will target, not what subdir the compiler package will be itself.
#    For example, we need a win-64 vs2008_win-32 package, so that we compile win-32
#    code on win-64 miniconda.
cross_compiler_target_platform:  # [win]
  - win-64                     # [win]
c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2017                     # [win]
c_compiler_version:            # [unix]
  - 11                         # [osx]
  - 9                          # [linux]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2017                     # [win]
cxx_compiler_version:          # [unix]
  - 11                         # [osx]
  - 9                          # [linux]
llvm_openmp:                   # [osx]
  - 11                         # [osx]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [linux64 or (osx and x86_64)]
  - gfortran                   # [aarch64 or ppc64le or armv7l or s390x]
  - flang                      # [win64]
fortran_compiler_version:      # [unix or win64]
  - 11                         # [osx and arm64]
  - 9                          # [osx and x86_64]
  - 9                          # [linux]
  - 5                          # [win64]
m2w64_c_compiler:              # [win]
  - m2w64-toolchain            # [win]
m2w64_cxx_compiler:            # [win]
  - m2w64-toolchain            # [win]
m2w64_fortran_compiler:        # [win]
  - m2w64-toolchain            # [win]
CMAKE_GENERATOR:               # [win]
  - NMake Makefiles            # [win]

cuda_compiler:                 # [linux64]
  - nvcc                       # [linux64]
cuda_compiler_version:
  - None
  - 10.2                       # [linux64]
cudnn:
  - undefined
  - 7                          # [linux64]

_libgcc_mutex:
  - 0.1 conda_forge
#
# Go Compiler Options
#

# The basic go-compiler with CGO disabled,
# It generates fat binaries without libc dependencies
# The activation scripts will set your CC,CXX and related flags
# to invalid values.
go_compiler:
  - go-nocgo
# The go compiler build with CGO enabled.
# It can generate fat binaries that depend on conda's libc.
# You should use this compiler if the underlying
# program needs to link against other C libraries, in which
# case make sure to add  'c,cpp,fortran_compiler' for unix
# and the m2w64 equivalent for windows.
cgo_compiler:
  - go-cgo
# The following are helpful variables to simplify go meta.yaml files.
target_goos:
  - linux                      # [linux]
  - darwin                     # [osx]
  - windows                    # [win]
target_goarch:
  - amd64                      # [x86_64]
target_goexe:
  -                            # [unix]
  - .exe                       # [win]
target_gobin:
  - '${PREFIX}/bin/'           # [unix]
  - '%PREFIX%\bin\'            # [win]

# Rust Compiler Options
rust_compiler:
  - rust
# Pin rust to <1.49 on osx-64 due to min deployment target req, cf. https://github.com/conda-forge/rust-feedstock/issues/73
rust_compiler_version:  # [osx and x86_64]
  - 1.46                # [osx and x86_64]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx and x86_64]
  - arm64-apple-darwin20.0.0   # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.9                       # [osx and x86_64]
target_platform:               # [win]
  - win-64                     # [win]
VERBOSE_AT:
  - V=1
VERBOSE_CM:
  - VERBOSE=1

# dual build configuration
channel_sources:
  - conda-forge,defaults                        # [not (aarch64 or armv7l or (osx and arm64) or s390x)]
  - conda-forge/label/rust_dev,conda-forge      # [osx and arm64]
  - conda-forge                                 # [aarch64]
  - conda-forge,c4armv7l,defaults               # [armv7l]
  - https://conda-web.anaconda.org/conda-forge  # [s390x]

channel_targets:
  - conda-forge main

cdt_name:  # [linux]
  - cos7   # [linux64 and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos6"]
  - cos7   # [linux64 and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos7"]
  - cos7   # [linux and aarch64]
  - cos7   # [linux and ppc64le]
  - cos7   # [linux and armv7l]
  - cos7   # [linux and s390x]

  - cos7   # [linux64 and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos6"]
  - cos7   # [linux64 and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos7"]

docker_image:                                   # [os.environ.get("BUILD_PLATFORM", "").startswith("linux-")]
  - quay.io/condaforge/linux-anvil-cos7-x86_64        # [os.environ.get("BUILD_PLATFORM") == "linux-64" and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos6"]
  - quay.io/condaforge/linux-anvil-cos7-x86_64  # [os.environ.get("BUILD_PLATFORM") == "linux-64" and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos7"]
  - quay.io/condaforge/linux-anvil-aarch64      # [os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]
  - quay.io/condaforge/linux-anvil-ppc64le      # [os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]
  - quay.io/condaforge/linux-anvil-armv7l       # [os.environ.get("BUILD_PLATFORM") == "linux-armv7l"]

  - quay.io/condaforge/linux-anvil-cuda:10.2       # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64" and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos6"]
  - quay.io/condaforge/linux-anvil-cos7-cuda:10.2  # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64" and os.environ.get("DEFAULT_LINUX_VERSION", "cos6") == "cos7"]

zip_keys:
  -                             # [unix]
    - c_compiler_version        # [unix]
    - cxx_compiler_version      # [unix]
    - fortran_compiler_version  # [unix]
  -
    - python
    - numpy
    - python_impl
  -                             # [linux64]
    - cudnn                     # [linux64]
    - cuda_compiler_version     # [linux64]
    - cdt_name                  # [linux64]
    - docker_image              # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]

# aarch64 specifics because conda-build sets many things to centos 6
# this can probably be removed when conda-build gets updated defaults
# for aarch64
cdt_arch: aarch64                       # [aarch64]
BUILD: aarch64-conda_cos7-linux-gnu     # [aarch64]

# armv7l specifics because conda-build sets many things to centos 6
# this can probably be removed when conda-build gets updated defaults
# for aarch64
cdt_arch: armv7l                          # [armv7l]
BUILD: armv7-conda_cos7-linux-gnueabihf   # [armv7l]

# TODO: remove these when run_exports are added to the packages.
pin_run_as_build:
  arpack:
    max_pin: x.x.x
  boost:
    max_pin: x.x.x
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  cairo:
    max_pin: x.x
  curl:
    max_pin: x
  dbus:
    max_pin: x
  fftw:
    max_pin: x
  flann:
    max_pin: x.x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  gdal:
    max_pin: x.x
  geotiff:
    max_pin: x.x.x
  glew:
    max_pin: x.x
  glpk:
    max_pin: x.x
  gmp:
    max_pin: x
  graphviz:
    max_pin: x
  harfbuzz:
    max_pin: x
  hdf4:
    max_pin: x.x
  isl:
    max_pin: x.x
  jasper:
    max_pin: x
  jpeg:
    max_pin: x
  libjpeg_turbo:
    max_pin: x
  json-c:
    max_pin: x.x
  jsoncpp:
    max_pin: x.x.x
  kealib:
    max_pin: x.x
  krb5:
    max_pin: x.x
  libblitz:
    max_pin: x.x
  libcurl:
    max_pin: x
  libevent:
    max_pin: x.x.x
  libffi:
    max_pin: x.x
  libgdal:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  libkml:
    max_pin: x.x
  libpng:
    max_pin: x.x
  librsvg:
    max_pin: x
  libsvm:
    max_pin: x.x
  libtiff:
    max_pin: x
  libxml2:
    max_pin: x.x
  libuuid:
    max_pin: x
  lz4-c:
    max_pin: x.x.x
  lzo:
    max_pin: x
  metis:
    max_pin: x.x
  mkl:
    max_pin: x
  mpfr:
    max_pin: x
  ncurses:
    max_pin: x.x
  netcdf-cxx4:
    max_pin: x.x
  netcdf-fortran:
    max_pin: x.x
  nettle:
    max_pin: x.x
  nlopt:
    max_pin: x.x.x
  nss:
    max_pin: x
  nspr:
    max_pin: x
  occt:
    max_pin: x.x
  openturns:
    max_pin: x.x
  openjpeg:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  pango:
    max_pin: x.x
  perl:
    max_pin: x.x.x
  poppler:
    max_pin: x.x
  qt:
    max_pin: x.x
  qtkeychain:
    max_pin: x.x
  readline:
    max_pin: x
  r-base:
    max_pin: x.x
    min_pin: x.x
  sox:
    max_pin: x.x.x
  spdlog:
    max_pin: x.x
  sqlite:
    max_pin: x
  tk:
    max_pin: x.x
  tiledb:
    max_pin: x.x
  vlfeat:
    max_pin: x.x.x
  vtk:
    max_pin: x.x.x
  xz:
    max_pin: x.x
  zeromq:
    max_pin: x.x  # [not win]
    max_pin: x.x.x  # [win]
  zlib:
    max_pin: x.x

# Pinning packages

# blas
libblas:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
libcblas:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
liblapack:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
liblapacke:
  - 3.8 *netlib  # [not (osx and arm64)]
  - 3.9 *netlib  # [osx and arm64]
blas_impl:
  - openblas
  - mkl          # [x86 or x86_64]
  - blis         # [x86 or x86_64]

abseil_cpp:
  - '20210324.2'
alsa_lib:
  - 1.2.3
arb:
  - '2.19'
arpack:
  - 3.7
arrow_cpp:
  - 4.0.1
aws_c_auth:
  - 0.6.1
aws_c_cal:
  - 0.5.11
aws_c_common:
  - 0.6.8
aws_c_event_stream:
  - 0.2.7
aws_c_http:
  - 0.6.5
aws_c_io:
  - 0.10.6
aws_c_mqtt:
  - 0.7.6
aws_c_s3:
  - 0.1.23
aws_checksums:
  - 0.1.11
aws_crt_cpp:
  - 0.14.5
aws_sdk_cpp:
  - 1.8.186
boost:
  - 1.74.0
boost_cpp:
  - 1.74.0
bzip2:
  - 1
cairo:
  - 1.16
cfitsio:
  - 3.470
cutensor:
  - 1
curl:
  - 7
dbus:
  - 1
exiv2:
  - 0.27
expat:
  - 2
ffmpeg:
  - '4.3'
fftw:
  - 3
flann:
  - 1.9.1
fmt:
  - '8'
fontconfig:
  - 2.13
freetype:
  - 2
gf2x:
  - '1.3'
gdk_pixbuf:
  - 2
gnuradio_core:
  - 3.8.3
gsl:
  - 2.6
gstreamer:
  - 1.18
gst_plugins_base:
  - 1.18
gdal:
  - '3.2'
geos:
  - 3.9.1
geotiff:
  - '1.6'
gflags:
  - 2.2
giflib:
  - 5.2
glew:
  - 2.1
glib:
  - '2'
glog:
  - '0.5'
glpk:
  - 4.65
gmp:
  - 6
google_cloud_cpp:
  - '1.29'
google_cloud_cpp_common:
  - 0.25.0
googleapis_cpp:
  - '0.10'
graphviz:
  - 2.47
grpc_cpp:
  - '1.38'
harfbuzz:
  - 2
hdf4:
  - 4.2
hdf5:
  - 1.10.6
icu:
  - 68
ipopt:
  - 3.14
isl:
  - '0.22'
jasper:
  # the first windows build of jasper was 2.0.14
  - 1  # [not (win or arm64)]
  - 2  # [win or arm64]
jpeg:
  - 9
libjpeg_turbo:
  - 2
json_c:
  - 0.15
jsoncpp:
  - 1.9.4
kealib:
  - 1.4
krb5:
  - 1.17.1
libarchive:
  - 3.5
libblitz:
  - 0.10
libcurl:
  - 7
libcrc32c:
  - 1.1
libdap4:
  - 3.20.6
libevent:
  - 2.1.10
libffi:
  - '3.3'
libgdal:
  - '3.2'
libgit2:
  - '1.1'
libiconv:
  - 1.16
libkml:
  - 1.3
libiio:
  - 0.21
libmatio:
  - 1.5
libmicrohttpd:
  - 0.9
libnetcdf:
  - 4.7.4
libopencv:
  - 4.5.2
libpcap:
  - '1.10'
libpng:
  - 1.6
libprotobuf:
  - '3.16'
librdkafka:
  - '1.6'
librsvg:
  - 2
libsecret:
  - 0.18
libspatialindex:
  - 1.9.3
libssh2:
  - 1
libsvm:
  - 3.21
libthrift:
  - 0.14.2
libtiff:
  - 4
libunwind:
  - 1
libv8:
  - 8.9.83
libwebp:
  - 1
libwebp_base:
  - 1
libxml2:
  - 2.9
libuuid:
  - 2.32.1
libzip:
  - 1
log4cxx:
  - 0.11.0
lz4_c:
  - 1.9.3
lzo:
  - 2
metis:
  - 5.1
mimalloc:
  - 1.6.3
mkl:
  - 2019
mpich:
  - 3
mpfr:
  - 4
mumps_mpi:
  - 5.2
mumps_seq:
  - 5.2
nccl:
  - 2
ncurses:
  - 6.2
netcdf_cxx4:
  - 4.3
netcdf_fortran:
  - 4.5
nettle:
  - '3.7'
nodejs:
  - 15
  - 14
  - 12
nss:
  - 3
nspr:
  - 4
nlopt:
  - '2.7'
ntl:
  - '11.4.3'
# we build for the oldest version possible of numpy for forward compatibility
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.18   # [not (osx and arm64)]
  - 1.18   # [not (osx and arm64)]
  - 1.18   # [not (osx and arm64)]
  - 1.19   # [osx and arm64]
  - 1.19
occt:
  - '7.5'
openblas:
  - 0.3.*
openexr:
  - 2.5
openjpeg:
  - '2.4'
openmpi:
  - 4
openssl:
  - 1.1.1
openturns:
  - '1.16'
orc:
  - 1.6.9
pango:
  - 1.42
pari:
  - 2.13.* *_pthread
perl:
  - 5.26.2  # [not (osx and arm64)]
  - 5.32.0  # [osx and arm64]
petsc:
  - 3.14
petsc4py:
  - 3.14
slepc:
  - 3.14
slepc4py:
  - 3.14
pcre:
  - '8'
pcre2:
  - '10.37'
pixman:
  - 0
poco:
  - 1.11.0
poppler:
  - '21.03'
proj:
  - 7.2.0
pybind11_abi:
  - 4
python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.6.* *_cpython    # [not (osx and arm64)]
  - 3.7.* *_cpython    # [not (osx and arm64)]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython   # [not (osx and arm64)]
  - cpython   # [not (osx and arm64)]
  - cpython
  - cpython
qt:
  - 5.12
qtkeychain:
  - '0.12'
re2:
  - 2021.06.01
readline:
  - "8"
rocksdb:
  - "6.10"
root_base:
  - 6.24.0
ruby:
  - 2.5
  - 2.6
# Pin rust to <1.49 on osx-64 due to min deployment target req, cf. https://github.com/conda-forge/rust-feedstock/issues/73
rust:     # [osx and x86_64]
  - 1.46  # [osx and x86_64]
r_base:
  - 4.0
  - 4.1
scotch:
  - 6.0.9
ptscotch:
  - 6.0.9
s2n:
  - 1.0.14
singular:
  - 4.2.0.p3
snappy:
  - 1
soapysdr:
  - '0.8'
sox:
  - 14.4.2
spdlog:
  - 1.8
sqlite:
  - 3
suitesparse:
  - 5
tbb:
  - 2020
tbb_devel:
  - 2020
thrift_cpp:
  - 0.14.2
tinyxml2:
  - 9
tk:
  - 8.6                # [not ppc64le]
tiledb:
  - '2.3'
uhd:
  - 4.1.0
vc:                    # [win]
  - 14                 # [win]
vlfeat:
  - 0.9.20
volk:
  - '2.5'
vtk:
  - 9.0.1
x264:
  - '1!161.*'
xerces_c:
  - 3.2
xrootd:
  - '5'
xz:
  - 5.2
zeromq:
  - 4.3.4
zlib:
  - 1.2
zstd:
  - '1.5'
