c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]

c_stdlib_version:              # [unix]
  - 2.12                       # [linux and x86_64]
  - 2.17                       # [linux and not x86_64]
  - 10.9                       # [osx and x86_64]
  - 11.0                       # [osx and arm64]

target_platform:
  - osx-64                     # [osx]
  - osx-arm64                  # [osx]
  - linux-64                   # [linux and x86_64]
  - linux-aarch64              # [linux and not x86_64]
  - win-64                     # [win]

channel_sources:
  - conda-forge,defaults

channel_targets:
  - conda-forge main
