{% set name = "ansible" %}
{% set version = "2.3.1.0" %}
{% set sha256 = "cd4b8f53720fcd0c351156b840fdd15ecfbec22c951b5406ec503de49d40b9f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - paramiko
    - jinja2
    - pyyaml
    - httplib2
    - pycrypto
    - six
    - shade
    - boto

test:
  imports:
    - ansible
    - ansible.constants
    - ansible.errors
    - ansible.utils
    
about:
  home: http://github.com/ansible/ansible
  license: GPL-3.0
  license_file: COPYING
  summary: 'Ansible is a radically simple IT automation platform'

  description: |
    Ansible is a radically simple IT automation platform 
    that makes your applications and systems easier to deploy.
  doc_url: https://www.ansible.com/
  dev_url: https://github.com/ansible/ansible

extra:
  recipe-maintainers:
    - souravsingh
    - brainstorm
