# see https://conda-forge.org/docs/maintainer/knowledge_base.html?#noarch-python
# for docs on providing multiple noarch platforms.
# see also this comment: https://github.com/conda-forge/devbio-napari-feedstock/pull/17#issuecomment-1249418027
# note this needs to be paired with `noarch_platforms` (plural!) on ../conda-forge.yml
# these keys have been chosen so they match conda's virtual packages for platform (__linux, __osx and __win)
noarch_platform:
  - linux  # [linux]
  - osx  # [osx]
  - win  # [win]
