c_stdlib:
  - sysroot                   # [linux]
  - macosx_deployment_target  # [osx]
c_stdlib_version:
  - 2.17                      # [linux]
  - 10.13                     # [osx and x86_64]
  - 11.0                      # [osx and arm64]
