# See https://github.com/google/tensorstore/blob/4f2d75d4f138574fba888f9b0cf3ec13c050ea52/setup.py#L113
c_stdlib_version:          # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]