[package]
name = "syster-python"
version = "0.3.1-alpha"
edition = "2021"
license = "MIT"
description = "Python bindings for the syster-base library"

[lib]
name = "syster_python"
crate-type = ["cdylib"]

[dependencies]
syster-base = { path = "syster-base", version = "0.3.1-alpha" }
pyo3 = { version = "0.23", features = ["extension-module"] }
