{% set name = "kubernetes"%}
{% set version = "1.7.14"%}

{% set sha256 = "1f3c05e60882f014236a1c93fac05afde49b0fcb67aabb4df0a11b96b5aa5d24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - go 1.8.*
    - rsync
    - make
    - toolchain

test:
  commands:
    - hyperkube --version

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Production-Grade Container Orchestration
  doc_url: https://v1-7.docs.kubernetes.io/docs/home/
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
