# Please consult conda-forge/core before doing this
c_stdlib_version:
  - "11"           # [osx and x86_64]
  - "2.17"         # [linux and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "11.3"                # [osx and x86_64]
os_version:
  linux_64: cos7
cdt_name:  # [linux]
  - cos7     # [linux]
