binutils_version:
  - 2.44

c_stdlib_version:                  # [osx]
  - 11.3                           # [osx]

MACOSX_DEPLOYMENT_TARGET:          # [osx]
  - 11.3                           # [osx]

c_compiler:                        # [unix]
  - clang                          # [unix]
c_compiler_version:
  - 19                             # [unix]
  - 2022                           # [not unix]

cxx_compiler:                      # [unix]
  - clangxx                        # [unix]
cxx_compiler_version:
  - 19                             # [unix]
  - 2022                           # [not unix]

triplet:                           # [linux or osx]
  - powerpc64le-conda-linux-gnu    # [linux]
  - aarch64-conda-linux-gnu        # [linux]
  - arm64-apple-darwin20.0.0       # [osx]

ctng_vendor:                       # [linux or osx]
  - conda                          # [linux]
  - conda                          # [linux]
  - unknown                        # [osx]

cross_target_platform:             # [linux or osx]
  - linux-ppc64le                  # [linux]
  - linux-aarch64                  # [linux]
  - osx-arm64                      # [osx]

ghc_triplet:                       # [linux or osx]
  - powerpc64le-unknown-linux-gnu  # [linux]
  - aarch64-unknown-linux-gnu      # [linux]
  - arm64-apple-darwin20.0.0       # [osx]

# Linux only
qemu_execve:                       # [linux]
  - qemu-execve-ppc64le            # [linux]
  - qemu-execve-aarch64            # [linux]

cross_abi_string:                  # [linux]
  - "OpenPOWER ELF V2 ABI"         # [linux]
  - "ARM aarch64"                  # [linux]

zip_keys:                          # [linux or osx]
  -                                # [linux or osx]
    - triplet                      # [linux or osx]
    - ctng_vendor                  # [linux or osx]
    - cross_target_platform        # [linux or osx]
    - ghc_triplet                  # [linux or osx]
    - qemu_execve                  # [linux]
    - cross_abi_string             # [linux]
