zip_keys:
  -
    - python
    - numpy
    - python_impl
python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
  - 3.10.* *_cpython
  - 3.11.* *_cpython
  - 3.11.* *_cpython
numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.21
  - 1.25
  - 1.26
  - 1.25
  - 1.26
  - 1.25
  - 1.26
python_impl:
  # part of a zip_keys: python, python_impl, numpy
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython
  - cpython