c_stdlib_version:          # [linux]
  - "2.17"                 # [linux]
c_stdlib_version:          # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]
