# these are the values `conda-forge` uses in their pinning file

# found at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

c_stdlib:

- sysroot

c_stdlib_version:

- 2.17