c_compiler_version:            # [linux]
  - 7                          # [linux]

cxx_compiler_version:          # [linux]
  - 7                          # [linux]

fortran_compiler_version:  # [unix]
  - 7                      # [linux]
  - 7                      # [osx]
