{% set name = "opentelemetry-exporter-prometheus" %}
{% set version = "1.12.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-exporter-prometheus-{{ version }}.tar.gz
  sha256: f10c6c243d69d5b63f755885b36a4ce8ef2cdf3e737c4e6bf00f32e87668f0a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - prometheus_client >=0.5.0,<1.0.0
    - opentelemetry-api >=1.10.0
    - opentelemetry-sdk >=1.10.0

test:
  imports:
    - opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-prometheus
  summary: Prometheus Metric Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
