arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

# The added keys below are needed to enable ppc64le/aarch64 CUDA builds; the linux64
# and win64 builds are already handled in the conda-forge-pinning feedstock. Once we
# migrate to enable CUDA builds on all supported platforms, these can be removed too.

docker_image:                                           # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-aarch64-cuda:11.0   # [aarch64 and os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]
   - quay.io/condaforge/linux-anvil-aarch64-cuda:11.1   # [aarch64 and os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]
   - quay.io/condaforge/linux-anvil-aarch64-cuda:11.2   # [aarch64 and os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]

c_compiler_version:        # [linux]
  - 9                      # [aarch64]
  - 9                      # [aarch64]
  - 9                      # [aarch64]
cxx_compiler_version:      # [linux]
  - 9                      # [aarch64]
  - 9                      # [aarch64]
  - 9                      # [aarch64]
fortran_compiler_version:  # [linux]
  - 9                      # [aarch64]
  - 9                      # [aarch64]
  - 9                      # [aarch64]

cuda_compiler:
  - nvcc

cuda_compiler_version:
  - 11.0                   # [aarch64]
  - 11.1                   # [aarch64]
  - 11.2                   # [aarch64]

cudnn:
  - undefined              # [aarch64]
  - undefined              # [aarch64]
  - undefined              # [aarch64]

cdt_name:  # [linux]
  - cos7   # [aarch64]
  - cos7   # [aarch64]
  - cos7   # [aarch64]
