CBUILD:
  - x86_64-conda-linux-gnu      # [linux]
  - x86_64-pc-windows-msvc      # [win]
  - dummy                       # [osx]

CHOST:
  - x86_64-conda-linux-gnu      # [linux]
# - wasm32-unknown-emscripten   # [linux]
  - x86_64-pc-windows-msvc      # [win]
  - dummy                       # [osx]

cross_target_platform:
  - linux-64                    # [linux]
# - emscripten-wasm32           # [linux]
  - win-64                      # [win]
  - dummy                       # [osx]

zip_keys:
  -
    - CHOST
    - cross_target_platform

channel_targets:
  - conda-forge llvm_rc

channel_sources:
  - conda-forge/label/llvm_rc,conda-forge
