# conda_build_config.yaml
python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
  - 3.14

is_python_min:
  - true   # Matches 3.10
  - false  # Matches 3.11
  - false  # Matches 3.12
  - false  # Matches 3.13
  - false  # Matches 3.14