# This is needed because of tree-sitter:
# https://github.com/tree-sitter/tree-sitter/issues/5217, fixed with tree-sitter 0.26.X, but is pinned to 0.25
# and because of v8 expecting memfd_create when linking
c_stdlib_version:          # [linux]
  - "2.28"                 # [linux]
# v8 is expecting _aligned_alloc when linking
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.15"                # [osx and x86_64]