# https://github.com/conda-forge/.cirun
github_actions_labels:  # [cuda_compiler_version != "None" and linux]
- cirun-openstack-gpu-2xlarge  # [(cuda_compiler_version or '')[:2] == '12' and linux]
- cirun-openstack-gpu-4xlarge  # [(cuda_compiler_version or '')[:2] == '11' and linux]

c_stdlib_version:          # [linux]
  - "2.30"                 # [linux]

megabuild:
- "true"  # [cuda_compiler_version != "None" and linux]
- "false"  # [cuda_compiler_version == "None" or not linux]
