channel_sources:
- conda-forge/label/gcc7,defaults   # [unix]
- conda-forge,defaults              # [win]
channel_targets:
- conda-forge gcc7                  # [unix]
- conda-forge main                  # [win]
c_compiler:
- gcc      # [linux]
- clang    # [osx]
cxx_compiler:
- gxx      # [linux]
- clangxx  # [osx]
