jobs:
- job: create_feedstocks
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  pool:
    vmImage: ubuntu-16.04
  strategy:
    maxParallel: 1
  timeoutInMinutes: 60
  steps:
  - script: |
      echo "Creating feedstocks from the recipe(s)."

      echo Build.Repository.ID is ${{ variables['Build.Repository.ID'] }}
      echo Build.Repository.Uri is ${{ variables['Build.Repository.Uri'] }}
      echo BUILD_REPOSITORY_ID is $BUILD_REPOSITORY_ID
      echo BUILD_REPOSITORY_NAME is $BUILD_REPOSITORY_NAME

      git config --global user.name "Azure Pipelines on github.com/conda-forge/staged-recipes"
      git config --global user.email "conda-forge@googlegroups.com"

      # source ./.travis_scripts/create_feedstocks
    displayName: Create feedstocks

