# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  condition: not(eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  pool:
    vmImage: macOS-12
  strategy:
    matrix:
      osx_64:
        CONFIG: osx64
    maxParallel: 8
  timeoutInMinutes: 360

  steps:
  - script: |
      export CI=azure
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build

  - publish: /Users/runner/Miniforge3/conda-bld/osx-64/
    artifact: conda_pkgs_osx
