MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.14                  # [osx]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]
